name: Development
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      with:
        host: 52.221.42.209
        username: root
        key: ${{ secrets.SSH_KEY_PROD }}
        port: 22
        command_timeout: 60m
        script: |
          cd /root/automate_chatgpt_nodered
          git checkout main
          git reset --hard HEAD
          git pull origin main
          source /opt/automate_chatgpt/bin/activate && pip install -r requirements.txt
          systemctl restart automate-chatgpt
          systemctl status automate-chatgpt
